# Header
menu:
  首页: /
  归档: /archives
  关于: /about

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: '#'
  twitter: '#'
  facebook: '#'
  dribbble: '#'
  rss: /atom.xml

# Links
links:
  #Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: